### ISSUE TITLE
您好，我按照你之前在GAIN中留言的配置DGL0.7.2+torch 1.10.0+cu113，仍会报错

### ISSUE THREAD

**Issue by msy0513** [LawsonAbs/GAIN#3]
Traceback (most recent call last):
  File "train.py", line 239, in <module>
    train(opt)
  File "train.py", line 27, in train
    opt=opt)
  File "F:\Desktop\GAIN-master\code\data.py", line 286, in __init__
    info = pickle.load(fr) # info <class 'dict'> key-value □ǣ□data, intrain_set
AttributeError: Can't get attribute 'DGLGraph' on <module 'dgl.heterograph' from 'E:\\anaconda\\envs\\env_pytorch\\lib\\site-packages\\dgl\\heterograph.py'

请问您遇到过这种问题吗？是如何解决的呢？

**Comment by msy0513** [comment]
我的电脑是cuda11.5版本 是否应安装更高版本的DGL-cuda11.5呢？

**Comment by LawsonAbs** [comment]
先看看是不是代码的问题，如果不是代码的问题可能大概率就是包的问题。自己手动debug看啥问题。

**Comment by LawsonAbs** [comment]
> 我的电脑是cuda11.5版本 是否应安装更高版本的DGL-cuda11.5呢？

如果是单纯的想熟悉GCN的代码可以学习，但如果是想做Document level relation extraction方向的工作，我不建议学这个代码了，这个模型过去两年了，不仅训练耗时，而且代码质量也不咋地。

**Comment by AAAsyj** [comment]
作者您好，请问您有什么推荐的Document level relation extraction方向的模型吗？想学习下，期待您的回复。
